### PR TITLE
#61 Delete Course

### PR DESCRIPTION
**Pull request by Thatcherk5765**
Added functionality to delete Courses in the manage page. When a user clicks on the delete button next to the course, they will be prompted with a confirmation. Upon accepting, the course will then be deleted.

### CODE REVIEW

**Review by dregerm1397 — APPROVED** [review]
Looks good to me. Might be good to change all of the alerts to be confirms in the future.

**Review by JeremyZyduck — APPROVED** [review]
Looks good. Works great. I would recommend changing the alerts to confirms though to stay consistent with the admin page.

**Review by JeremyZyduck — CHANGES_REQUESTED** [review]
Not updated from most recent commits to the staging branch

**Review by JeremyZyduck — APPROVED** [review]
Changes look good

**Pull request merged**
