### PR TITLE
#18 edit user modal

### PR DESCRIPTION
**Pull request by LillianGomez**

### CODE REVIEW

**Review by dregerm1397 — CHANGES_REQUESTED** [review]
There seems to be a .idea folder that was created that contains a bunch of files that I'm not sure that they do. I would suggest removing the .ideas folder.

Also there are changes to the package-lock.json file. Please revert them to their previous settings.

Otherwise the rest of the changes look good.

**Review by dregerm1397 — APPROVED** [review]

**Review by dregerm1397 — COMMENTED** [review]
I see where you created the modal but does this connect to the api function to edit a user?

**Review by LiamKnutson — CHANGES_REQUESTED** [review]
The modal itself looks good, but I don't believe this fulfills the entire criteria for the story. Namely, the following:

- Edit User button should be connected so that the existing design has functional use

Please correct me if I am wrong, but I do not see the button being connected to the edit user functionality. Once this is added, I believe all the criteria will be fulfilled.

**Review by JeremyZyduck — APPROVED** [review]

**Review by LiamKnutson — APPROVED** [review]
Everything looks good!

**Pull request merged**
